### ISSUE TITLE
Dummy_rgb_dataset

### ISSUE THREAD

**Issue by nikky4D** [chihyaoma/cyclical-visual-captioning#2]
I'm using the dummy_rgb_dataset for my own development. Do I still need to download anet_detection_vg_fc6_feat_100rois?

**Comment by chihyaoma** [comment]
If I recall correctly, yes, you do. The `anet_detection_vg_fc6_feat_100rois.h5` file is only 2.9 GB though. 

Please let me know if you have other questions.

**Comment by nikky4D** [comment]
Thank you. The dummy_rgb_dataset is a wonderful idea and helped me immensely in my experiments.
